// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trias.proto

package tm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecuteContractRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	CheckMD5             string   `protobuf:"bytes,2,opt,name=checkMD5,proto3" json:"checkMD5,omitempty"`
	Command              string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	ContractName         string   `protobuf:"bytes,4,opt,name=contractName,proto3" json:"contractName,omitempty"`
	ContractType         string   `protobuf:"bytes,5,opt,name=contractType,proto3" json:"contractType,omitempty"`
	VmVersion            string   `protobuf:"bytes,6,opt,name=vmVersion,proto3" json:"vmVersion,omitempty"`
	Sequence             string   `protobuf:"bytes,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	User                 string   `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	Signature            string   `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	Opration             string   `protobuf:"bytes,11,opt,name=opration,proto3" json:"opration,omitempty"`
	//XXX_NoUnkeyedLiteral struct{} `json:"-"`
	//XXX_unrecognized     []byte   `json:"-"`
	//XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteContractRequest) Reset()         { *m = ExecuteContractRequest{} }
func (m *ExecuteContractRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteContractRequest) ProtoMessage()    {}
func (*ExecuteContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caf2bba411ca9dfc, []int{0}
}

func (m *ExecuteContractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteContractRequest.Unmarshal(m, b)
}
func (m *ExecuteContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteContractRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteContractRequest.Merge(m, src)
}
func (m *ExecuteContractRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteContractRequest.Size(m)
}
func (m *ExecuteContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteContractRequest proto.InternalMessageInfo

func (m *ExecuteContractRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ExecuteContractRequest) GetCheckMD5() string {
	if m != nil {
		return m.CheckMD5
	}
	return ""
}

func (m *ExecuteContractRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecuteContractRequest) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ExecuteContractRequest) GetContractType() string {
	if m != nil {
		return m.ContractType
	}
	return ""
}

func (m *ExecuteContractRequest) GetVmVersion() string {
	if m != nil {
		return m.VmVersion
	}
	return ""
}

func (m *ExecuteContractRequest) GetSequence() string {
	if m != nil {
		return m.Sequence
	}
	return ""
}

func (m *ExecuteContractRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ExecuteContractRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ExecuteContractRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ExecuteContractRequest) GetOpration() string {
	if m != nil {
		return m.Opration
	}
	return ""
}

type ExecuteContractResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	//XXX_NoUnkeyedLiteral struct{} `json:"-"`
	//XXX_unrecognized     []byte   `json:"-"`
	//XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteContractResponse) Reset()         { *m = ExecuteContractResponse{} }
func (m *ExecuteContractResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteContractResponse) ProtoMessage()    {}
func (*ExecuteContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caf2bba411ca9dfc, []int{1}
}

func (m *ExecuteContractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteContractResponse.Unmarshal(m, b)
}
func (m *ExecuteContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteContractResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteContractResponse.Merge(m, src)
}
func (m *ExecuteContractResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteContractResponse.Size(m)
}
func (m *ExecuteContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteContractResponse proto.InternalMessageInfo

func (m *ExecuteContractResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ExecuteContractResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ExecuteContractResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*ExecuteContractRequest)(nil), "tm.ExecuteContractRequest")
	proto.RegisterType((*ExecuteContractResponse)(nil), "tm.ExecuteContractResponse")
}

func init() { proto.RegisterFile("trias.proto", fileDescriptor_caf2bba411ca9dfc) }

var fileDescriptor_caf2bba411ca9dfc = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xbd, 0x4e, 0x33, 0x31,
	0x10, 0x54, 0xfe, 0x13, 0xe7, 0x93, 0x3e, 0xc9, 0x12, 0x60, 0x05, 0x8a, 0x28, 0x55, 0xaa, 0x14,
	0x20, 0x9e, 0x00, 0x68, 0x90, 0x42, 0x71, 0xa0, 0x34, 0x54, 0x8b, 0x6f, 0x95, 0x58, 0x60, 0xfb,
	0xf0, 0xee, 0x45, 0xf0, 0xa2, 0x3c, 0x0f, 0xb2, 0xef, 0x2e, 0x21, 0x90, 0x6e, 0x67, 0x76, 0x47,
	0x33, 0x37, 0x67, 0x31, 0xe6, 0x60, 0x80, 0x16, 0x45, 0xf0, 0xec, 0x65, 0x9b, 0xed, 0xec, 0xab,
	0x2d, 0x4e, 0xef, 0x3e, 0x50, 0x97, 0x8c, 0x37, 0xde, 0x71, 0x00, 0xcd, 0x19, 0xbe, 0x97, 0x48,
	0x2c, 0x95, 0x18, 0x40, 0x9e, 0x07, 0x24, 0x52, 0xad, 0x69, 0x6b, 0x3e, 0xca, 0x1a, 0x28, 0x27,
	0x62, 0xa8, 0x37, 0xa8, 0x5f, 0x97, 0xb7, 0xd7, 0xaa, 0x9d, 0x56, 0x3b, 0x1c, 0x55, 0xda, 0x5b,
	0x0b, 0x2e, 0x57, 0x9d, 0x4a, 0x55, 0x43, 0x39, 0x13, 0xff, 0x74, 0x6d, 0xf1, 0x00, 0x16, 0x55,
	0x37, 0xad, 0x0f, 0xb8, 0x9f, 0x37, 0x4f, 0x9f, 0x05, 0xaa, 0xde, 0xe1, 0x4d, 0xe4, 0xe4, 0x85,
	0x18, 0x6d, 0xed, 0x0a, 0x03, 0x19, 0xef, 0x54, 0x3f, 0x1d, 0xec, 0x89, 0x98, 0x8d, 0xe2, 0x07,
	0x38, 0x8d, 0x6a, 0x50, 0x65, 0x6b, 0x70, 0x54, 0xb2, 0xb1, 0x48, 0x0c, 0xb6, 0x50, 0xc3, 0x69,
	0x6b, 0xde, 0xc9, 0xf6, 0x84, 0x94, 0xa2, 0x5b, 0x12, 0x06, 0x35, 0x4a, 0xaa, 0x34, 0x47, 0x05,
	0x99, 0xb5, 0x03, 0x2e, 0x03, 0x2a, 0x51, 0x79, 0xed, 0x88, 0xe8, 0xe5, 0x8b, 0x00, 0x1c, 0x83,
	0x8c, 0x2b, 0xaf, 0x06, 0xcf, 0x9e, 0xc5, 0xd9, 0x9f, 0x5e, 0xa9, 0xf0, 0x8e, 0x30, 0x1a, 0x69,
	0x9f, 0x63, 0x6a, 0xb5, 0x97, 0xa5, 0x39, 0xd6, 0x66, 0x91, 0x08, 0xd6, 0x58, 0x37, 0xda, 0xc0,
	0x78, 0x9d, 0x03, 0x43, 0xdd, 0x66, 0x9a, 0x2f, 0xb5, 0x38, 0x59, 0x99, 0xc0, 0x25, 0xbc, 0x2d,
	0x41, 0x6f, 0x8c, 0xc3, 0x47, 0x0c, 0x5b, 0xa3, 0x51, 0xde, 0x8b, 0xff, 0xbf, 0x5c, 0xe5, 0x64,
	0xc1, 0x76, 0x71, 0xfc, 0x17, 0x4f, 0xce, 0x8f, 0xee, 0xaa, 0x98, 0x2f, 0xfd, 0xf4, 0x4a, 0xae,
	0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xd3, 0xbd, 0xb4, 0x34, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VirtualMachineServiceClient is the client API for VirtualMachineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualMachineServiceClient interface {
	ExecuteContract(ctx context.Context, in *ExecuteContractRequest, opts ...grpc.CallOption) (*ExecuteContractResponse, error)
}

type virtualMachineServiceClient struct {
	cc *grpc.ClientConn
}

func NewVirtualMachineServiceClient(cc *grpc.ClientConn) VirtualMachineServiceClient {
	return &virtualMachineServiceClient{cc}
}

func (c *virtualMachineServiceClient) ExecuteContract(ctx context.Context, in *ExecuteContractRequest, opts ...grpc.CallOption) (*ExecuteContractResponse, error) {
	out := new(ExecuteContractResponse)
	err := c.cc.Invoke(ctx, "/tm.VirtualMachineService/ExecuteContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualMachineServiceServer is the server API for VirtualMachineService service.
type VirtualMachineServiceServer interface {
	ExecuteContract(context.Context, *ExecuteContractRequest) (*ExecuteContractResponse, error)
}

func RegisterVirtualMachineServiceServer(s *grpc.Server, srv VirtualMachineServiceServer) {
	s.RegisterService(&_VirtualMachineService_serviceDesc, srv)
}

func _VirtualMachineService_ExecuteContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).ExecuteContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tm.VirtualMachineService/ExecuteContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).ExecuteContract(ctx, req.(*ExecuteContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtualMachineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tm.VirtualMachineService",
	HandlerType: (*VirtualMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteContract",
			Handler:    _VirtualMachineService_ExecuteContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trias.proto",
}
